name: Create Executables

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyserial pyinstaller

      - name: Create the executable
        run: pyinstaller --onefile ktool.py

      - name: Upload the Mac executable
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: ktool-mac
          path: dist/ktool

      - name: Upload the Mac-10 executable
        if: matrix.os == 'macos-10.15'
        uses: actions/upload-artifact@v2
        with:
          name: ktool-mac-10
          path: dist/ktool

      - name: Upload the Linux executable
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: ktool-linux
          path: dist/ktool

      - name: Upload the Windows executable
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: ktool-win.exe
          path: dist/ktool.exe
